### ISSUE TITLE
Build failed on Linux

### ISSUE THREAD

**Issue by aaowens** [davidanthoff/ReadStat.jl#28]
```
INFO: Changing Directory to /home/andrew/.julia/v0.6/ReadStat/deps/src/readstat-0.1.1
/usr/bin/ld: cannot find -llzma
collect2: error: ld returned 1 exit status
make: *** [libreadstat.la] Error 1
==============================[ ERROR: ReadStat ]===============================

LoadError: failed process: Process(`make`, ProcessExited(2)) [2]
while loading /home/andrew/.julia/v0.6/ReadStat/deps/build.jl, in expression starting on line 34

================================================================================

julia> versioninfo()
Julia Version 0.6.0
Commit 9036443 (2017-06-19 13:05 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
```

I haven't been able to find out what llzma is through Google, or how I should install it. Is there some dependency I need before I can use ReadStat?

**Comment by evanmiller** [comment]
Hi, liblzma is provided as part of XZ utils (https://tukaani.org/xz/). It's no longer required by ReadStat, so if you can get your hands on the dev version of ReadStat you should be ok.

**Comment by aaowens** [comment]
I fixed it by installing the liblzma-dev package on Ubuntu. I had liblzma and xz-utils, but it wasn't enough.

**Comment by davidanthoff** [comment]
@aaowens, would be great if you could open a PR that adds the steps you had to take to the README!

In general it would be nice if we could track the readstat upstream versions here, but my last experience with getting the Windows binaries compiled for WinRPM made me promise to myself that I would never ever touch those suse build services again, it was just a complete nightmare how much time it took to get that working... I think maybe a better strategy is to wait until BinDeps2 is released and maybe that will have a better story for providing binaries on windows for julia packages...

**Comment by aaowens** [comment]
I can try, but it's not a complete solution. For example, I don't have admin access to a linux cluster I'd like to try ReadStat on. The build also fails there.

**Comment by davidanthoff** [comment]
``master`` now uses precompiled binaries, which should solve this.
