### ISSUE TITLE
Not currently compatible with DataFrames 0.11 (with missings)

### ISSUE THREAD

**Issue by nickeubank** [davidanthoff/ReadStat.jl#30]
Looks like loading ReadStats package causes DataFrames to revert to 0.10 (pre-missings). This something adaptable? Sounds like Missings are here to stay.

**Comment by davidanthoff** [comment]
I was planning to remove the dependency of ReadStat.jl on DataFrames.jl entirely, and then folks can use https://github.com/davidanthoff/StatFiles.jl (which uses ReadStat.jl under the hood) to load stuff into DataFrames. The main benefit of that is that it will support both DataFrames.jl v0.10 and v0.11 at the same time.

Haven't cleared this with @evanmiller, so he might have a different plan :)

**Comment by davidanthoff** [comment]
Readstat.jl no longer supports DataFrames.jl, instead you should use StatFiles.jl for that, and it supports all versions of DataFrames.jl.
